version: '3.1'
services:

  web:
    image: httpd:2.2
    container_name: web
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      web_fess:
      lucee_web:

networks:
  lucee_web:
  web_fess: